theme = "solarized-dark"
[icons]
name = "awesome"
# [icons.overrides]\
# backlight_empty = "☀️ "\
# backlight_partial1 = "☀️ "\
# backlight_partial2 = "☀️ "\
# backlight_partial3 = "☀️ "\
# backlight_full = "☀️ "\

# [[block]]\
# block = "pacman"\
# \
# [[block]]\
# block = "backlight"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = "{percentage}%"

# [[block]]\
# block = "net"\
# device = "wlan0"\
# speed_down = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
