source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/fzf.kak"
map global normal '<C-p>' ': fzf-mode<ret>'
plug "andreyorst/powerline.kak"
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force
}

eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
plug "danr/kakoune-easymotion"
